---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${ { secrets.DOCKERHUB_USER } }
          password: ${ { secrets.DOCKERHUB_TOKEN } }
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      # - name: Save state
      #   run: echo "{name}={value}" >> $GITHUB_STATE
      # - name: Set output
      #   run: echo "{name}={value}" >> $GITHUB_OUTPUT
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
